name: test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.20
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Test
        # `pnpm lint` is not emit error exit code, so we need to check the output
        run: pnpm build | tee >(tail -n1 | grep -q 'Failed') && exit 1 || exit 0